import type { Article, ArticleRanking, ArticleSummary } from "@prisma/client";

type ArticleWithRelations = Article & {
  ranking: ArticleRanking | null;
  summary: ArticleSummary | null;
};

function tierColor(tier: string): string {
  switch (tier) {
    case "Essential":
      return "#dc2626";
    case "Important":
      return "#f59e0b";
    case "Optional":
      return "#6b7280";
    default:
      return "#6b7280";
  }
}

function articleCard(article: ArticleWithRelations): string {
  const tier = article.ranking?.tier || "Unranked";
  const score = article.ranking?.score?.toFixed(1) || "—";
  const header =
    article.ranking?.suggested_header || article.title || "Untitled";
  const summary = article.summary?.summary_text || "";
  const bullets = article.summary?.why_it_matters || [];
  const implications = article.summary?.implications || "";

  return `
    <div style="margin-bottom:24px;padding:20px;border:1px solid #e5e7eb;border-radius:8px;border-left:4px solid ${tierColor(tier)};">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
        <h3 style="margin:0;font-size:18px;color:#111827;">${header}</h3>
        <span style="background:${tierColor(tier)};color:white;padding:2px 10px;border-radius:12px;font-size:12px;font-weight:600;white-space:nowrap;">
          ${tier} ${score}
        </span>
      </div>
      <p style="color:#4b5563;font-size:14px;line-height:1.6;margin:8px 0;">${summary}</p>
      ${
        bullets.length > 0
          ? `<ul style="margin:8px 0;padding-left:20px;">${bullets.map((b) => `<li style="color:#374151;font-size:13px;line-height:1.5;margin-bottom:4px;">${b}</li>`).join("")}</ul>`
          : ""
      }
      ${implications ? `<p style="color:#6b7280;font-size:13px;font-style:italic;margin:8px 0;">${implications}</p>` : ""}
      <a href="${article.url}" style="color:#2563eb;font-size:13px;text-decoration:none;" target="_blank">Read full article &rarr;</a>
    </div>`;
}

export function generateNewsletterHtml(
  title: string,
  articles: ArticleWithRelations[]
): string {
  const date = new Date().toLocaleDateString("en-AU", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Group by tier
  const essential = articles.filter(
    (a) => a.ranking?.tier === "Essential"
  );
  const important = articles.filter(
    (a) => a.ranking?.tier === "Important"
  );
  const optional = articles.filter(
    (a) =>
      a.ranking?.tier === "Optional" || !a.ranking?.tier
  );

  function tierSection(
    tierName: string,
    items: ArticleWithRelations[]
  ): string {
    if (items.length === 0) return "";
    return `
      <div style="margin-bottom:32px;">
        <h2 style="font-size:20px;color:${tierColor(tierName)};border-bottom:2px solid ${tierColor(tierName)};padding-bottom:8px;margin-bottom:16px;">
          ${tierName} (${items.length})
        </h2>
        ${items.map(articleCard).join("")}
      </div>`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;">
  <div style="max-width:680px;margin:0 auto;background:white;padding:32px;">
    <div style="text-align:center;margin-bottom:32px;padding-bottom:24px;border-bottom:2px solid #e5e7eb;">
      <h1 style="margin:0;font-size:28px;color:#111827;">${title}</h1>
      <p style="color:#6b7280;font-size:14px;margin-top:8px;">${date}</p>
      <p style="color:#9ca3af;font-size:12px;margin-top:4px;">Curated by AI Factory &bull; GAI Insights</p>
    </div>

    ${tierSection("Essential", essential)}
    ${tierSection("Important", important)}
    ${tierSection("Optional", optional)}

    <div style="text-align:center;padding-top:24px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px;">
      <p>Generated by AI Factory &bull; <a href="https://gaiinsights.com" style="color:#9ca3af;">GAI Insights</a></p>
    </div>
  </div>
</body>
</html>`;
}
